### ISSUE TITLE
support `--config`

### ISSUE THREAD

**Issue by aladdin-add** [eslint/create-config#23]
refs: https://github.com/eslint/create-config/issues/22
1. `--config` to use any `eslint-config-xxx` npm packages, and skip asking questions. e.g.
```sh
$ npm init @eslint/config --config react-app # extends eslint-config-react-app
$ npm init @eslint/config --config airbnb # extends eslint-config-airbnb
```

~~2. `--yes` to skip asking questions(similar to `npm init --yes`), the default format is js.(other formats will be going away in the new config)~~

**Comment by nzakas** [comment]
Sorry, I missed this.

I’m not sure I understand the point of `—config`. What does this accomplish?

For `—yes`, most questions aren’t yes or no answers, so I’m not sure if this makes sense. Can you explain more about what you’re thinking here?

**Comment by aladdin-add** [comment]
> I’m not sure I understand the point of —config. What does this accomplish?


currently `@eslint/create-config` support to init 4 popular style guides:
* airbnb
* standard
* google
* xo

however, there is still a pretty big numbers of users were using others (e.g. `eslint-config-react-app`), while we don't want to maintain all these style guides in the list. the `--config` is to allow users to input a npm pakcage name(eslint-config-xxx) to support all others. so users can run `--config react-app`.

the `--yes` is a quick way to init an eslint config to enforce a popular style guide(I was assuming it's most users want to do). The other questions have the following defaults:
```sh
✔ How would you like to use ESLint? · style
✔ What type of modules does your project use? · esm
✔ Which framework does your project use? · none
✔ Does your project use TypeScript? · No / Yes
✔ Where does your code run? · node
✔ How would you like to define a style for your project? · guide
✔ Which style guide do you want to follow? · standard // => only ask the question if no `--config`
✔ What format do you want your config file to be in? · JavaScript
Checking peerDependencies of eslint-config-standard@latest
The config that you've selected requires the following dependencies:

eslint-config-standard@latest
✔ Would you like to install them now with npm? · No / Yes
```

**Comment by nzakas** [comment]
Ah, I think I understand the point of `—config` now, thanks. My only question: do we have a generic way to load peerdependencies from random packages? I thought we had to hardcode that to make Airbnb work, for example?

I’m still not sure about `—yes` — again, we just don’t have that many yes/no questions and I don’t think people will understand what this means.

**Comment by snitin315** [comment]
Perhaps we need a better name for `--yes`, maybe `--default` or `--force`. 

>To generate a project without questions. When enabled, the default answer for each question will be used.

webpack-cli has [`webpack init --force`](https://webpack.js.org/api/cli/#init)

**Comment by aladdin-add** [comment]
👍 `--default` sounds a better choice for me. (`--force` has a slight signal: "this is somewhat dangerous"- like `git push --force` 😄 )

**Comment by aladdin-add** [comment]
it was using `npm show peerdependencies`, and then installing them. so in theory it should be working for others.
https://github.com/eslint/create-config/blob/9cee9035e9c32d58be23611859490e7e22e51c65/lib/init/npm-utils.js#L69-L73

plus, most of these peerdependencies can be dependencies, once the new config shipped.

**Comment by nzakas** [comment]
I’m still not sold on having an option that accepts all of the defaults, especially because we may change defaults at some point. 

@eslint/eslint-tsc thoughts?

**Comment by aladdin-add** [comment]
to be clearer, the `--default` is not to enforce any style guide; it's to skip other questions, but let the user select a style guide.

re other questions: in most cases they should have been configed in the shared configs. e.g. eslint-config-standard:
https://github.com/standard/eslint-config-standard/blob/879fd8ecb1070e7761ab169be27313dc5c4f3899/.eslintrc.json#L2-L13

**Comment by btmills** [comment]
I'm familiar with the `--yes` idiom from other CLI tools, but can you explain more about the motivation for having it here? For example, are we hoping to support unsupervised, non-interactive installs via `npm init`? That's where I see `--yes` used most frequently.

**Comment by aladdin-add** [comment]
> For example, are we hoping to support unsupervised, non-interactive installs via npm init.

yes, it's what I was imaging. it's to use a shared config(e.g. eslint-config-airbnb). If the `--config` is provided, it will create an eslint config without any questions. But if no `--config`, we don't know which shared config should be used, the `Which style guide do you want to follow` is the only question.

**Comment by btmills** [comment]
Could we get away with just `--config`? That could skip the wizard since shared configs typically override those most common settings. Then I could see shared configs including a one-line command for users to run as you’ve outlined in your original post at the top of the thread. If someone’s providing a shared config, do you think it’s important that we still run the wizard?

**Comment by aladdin-add** [comment]
👍 sounds great! I'll update the OP.

**Comment by nzakas** [comment]
I’m 👍 to just the —config option.

**Comment by harish-sethuraman** [comment]
Just trying to understand more, when we use `--config` what format of config are we going to generate? `json` or `js` or `.eslitnrc`? What values do we prefill with (Like for the question `does your project use typescript?`)? and for other questions? 

<img width="372" alt="Screenshot 2022-05-05 at 8 34 03 AM" src="https://user-images.githubusercontent.com/32865581/166858013-40fd48d6-52a7-4b32-9ae0-7c9397c4fe29.png">

**Comment by aladdin-add** [comment]
> what format of config are we going to generate? json or js or .eslitnrc?

I'd go for `eslintrc.js/cjs` (other formats will be went away in the new config)

expect for the new added `"which package manager...?"`, seems all other questions are no longer needed, as they would have been configured in the shared config. e.g. `eslint-config-standard`:
https://github.com/standard/eslint-config-standard/blob/bcd019906cd379be04ef8e6347e108bad4fc448d/.eslintrc.json#L2-L13

**Comment by harish-sethuraman** [comment]
> as they would have been configured in the shared config. e.g. eslint-config-standard

Do we have any util to fetch the shared config from the package? 

Also since we are going to use default settings, answer for `which framework does your project use?` is going to use be `none of these` right?

PS: I can try implementing this :)

**Comment by aladdin-add** [comment]
> Do we have any util to fetch the shared config from the package?

I don't think it's needed - we can just assume all the configs were in the shared config. let's say `eslint-config-foo`, we just need to init the config:

```js
module.exports = {extends: ["foo"]};
```

and install its peerdeps.

**Comment by nzakas** [comment]
The `—config` option should still have all other questions asked, including what format the config file should be. It just replaces the question of which shared config to use

**Comment by btmills** [comment]
@nzakas seems you and I are on different pages here. @aladdin-add's original use case, clarified in https://github.com/eslint/create-config/issues/23#issuecomment-1087163068, was to have a non-interactive setup that could be run in an unsupervised scenario.

**Comment by nzakas** [comment]
Ah, I misunderstood, apologies. Skipping around between too many issues. 

In that case, I agree that the default output format should be a JS file.

**Comment by harish-sethuraman** [comment]
`Also since we are going to use default settings, answer for which framework does your project use? is going to use be none of these right?`

I think we missed this question alone

**Comment by nzakas** [comment]
Yes, the answer should be “none of these”.

We can’t support TypeScript by default in this mode, and I think that’s fine.
